# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yorce
# "service" is the name of this project. This will also be added to your AWS resource names.
service: prueba

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
